# Generated by Django 5.1.7 on 2025-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_alter_employee_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_behavior_data',
            field=models.JSONField(default=dict),
        ),
    ]
