# Generated by Django 5.1.7 on 2025-03-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_employee_user_behavior_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_behavior_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
