# Generated by Django 5.1.7 on 2025-03-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_alter_employee_user_behavior_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_behavior_data',
        ),
    ]
