# Generated by Django 5.1.7 on 2025-03-19 16:05

import employee_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0005_remove_employee_user_behavior_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=50, validators=[employee_register.models.validate_fullname]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=50, validators=[employee_register.models.validate_fullname]),
        ),
    ]
