# Generated by Django 5.1.7 on 2025-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
