# Generated by Django 5.1.7 on 2025-03-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_attachement_alter_contact_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=122)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
